pipeline:
    name: Helm Charts
    identifier: Helm_Charts
    projectIdentifier: CD_Examples
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Helm Charts
              identifier: Helm_Charts
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: helmchart
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: helmchart
                                        type: HelmChart
                                        spec:
                                            store:
                                                type: Http
                                                spec:
                                                    connectorRef: Bitnami_Helm_Repo
                                            valuesPaths:
                                                - values.yaml
                                            chartName: nginx
                                            chartVersion: ""
                                            helmVersion: V3
                                            skipResourceVersioning: false
                                            commandFlags:
                                                - commandType: Pull
                                                  flag: --verify
                  infrastructure:
                      environmentRef: test
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: cddoc
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
