pipeline:
    name: Kustomize Quickstart
    identifier: Kustomize_Quickstart
    projectIdentifier: CD_Examples
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Kustomize
              identifier: Kustomize
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginx
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: kustomize
                                        type: Kustomize
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: kustomize_repo
                                                    gitFetchType: Branch
                                                    folderPath: kustomize/helloWorld
                                                    branch: main
                                            pluginPath: ""
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: kustomize
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: cddoc
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
