pipeline:
    name: Tiny HTTP GCR
    identifier: Tiny_HTTP_GCR
    projectIdentifier: CD_Examples
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: tweetapp
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: cddoc
                          namespace: default
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: make run
                                identifier: make_run
                                spec:
                                    connectorRef: DockerHub
                                    image: golang:1.17.3
                                    command: make run
                                    privileged: false
                          - step:
                                type: BuildAndPushGCR
                                name: Build and Push to GCR
                                identifier: Build_and_Push_to_GCR
                                spec:
                                    connectorRef: GCP_Example
                                    host: us.gcr.io
                                    projectID: harnessplayground
                                    imageName: harness/sally
                                    tags:
                                        - <+pipeline.sequenceId>
                                    optimize: true
              variables: []
