pipeline:
    name: AWS Build
    identifier: AWS_Build
    allowStageExecutions: false
    projectIdentifier: CD_Examples
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: tweetapp
                build: <+input>
    stages:
        - stage:
              name: foo
              identifier: foo
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: VM
                      spec:
                          type: Pool
                          spec:
                              identifier: foo
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: echo
                                identifier: echo
                                spec:
                                    shell: Sh
                                    command: echo
