pipeline:
    name: Policy
    identifier: Policy
    allowStageExecutions: false
    projectIdentifier: CD_Examples
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Test
              identifier: Test
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                name: Get version
                                identifier: Get_version
                                spec:
                                    url: https://app.harness.io/prod1/pm/api/v1/system/version
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                timeout: 10s
                          - step:
                                type: Policy
                                name: Version Policy
                                identifier: Version_Policy
                                spec:
                                    policySets:
                                        - Version
                                    type: Custom
                                    policySpec:
                                        payload: <+pipeline.stages.Test.spec.execution.steps.Get_version.output.httpResponseBody>
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: Policy Step Expressions
                                identifier: Policy_Step_Expressions
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |+
                                                <+pipeline.stages.Test.spec.execution.steps.Version_Policy.output.status>


                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                  serviceDependencies: []
              tags: {}
