pipeline:
    name: secrets
    identifier: secrets
    projectIdentifier: CD_Examples
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: secrets
              identifier: secrets
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: vars
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: DockerHub
                                          imagePath: library/nginx
                                          tag: stable-perl
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: vars
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: cddoc
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: echo secret
                                identifier: echo_secret
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo <+secrets.getValue("linebreaks")>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: secrets
                                identifier: secrets
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                echo '<+secrets.getValue("linebreaks")>' | base64 -d > /tmp/secretvalue.txt

                                                cat >/tmp/secretvalue.txt << 'EOF'
                                                MySecret:<+secrets.getValue("linebreaks")>
                                                EOF
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: decode
                                identifier: decode
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo <+secrets.getValue("linebreaks")> | base64 -d
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
